---
- hosts: webservers
  remote_user: root

  tasks:
  - name: Install epel
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present
  - name: Start service
    service:
      name: nginx
      state: started
  - name: Creates directory
    file:
      path: /var/www/example.com/html
      state: directory
      owner: nginx
      group: nginx
      mode: 0775
      recurse: yes

  - name: Copy default setting
    template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf owner=root mode=0644
  - name: Copy virtual host configuation
    template: src=templates/example.com.conf dest=/etc/nginx/conf.d/example.com.conf owner=root mode=0644
  - name: Copy static file
    template: src=static_file/index.html dest=/var/www/example.com/html owner=nginx group=nginx mode=0644
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted