Vagrant.configure(2) do |config|
    
  config.vm.provider "virtualbox"
    
  config.vm.provider "virtualbox" do |vb|
  end

  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.10.100"

  config.vm.provider "virtualbox" do |vb|
  	vb.gui = true
 	vb.memory = "2048"
  end
  
#  config.vm.provision "shell", inline: <<-SHELL
  $script = <<-SCRIPT
    sudo yum update -y     
    sudo yum install -y wget
    sudo yum install -y curl
    sudo yum install -y vim
    sudo yum install -y git    
    sudo yum install -y build-essential
    sudo yum install -y unzip
    sudo setenforce 0
    sudo yum install -y epel-release
    sudo yum install -y ansible
  SCRIPT
  
  config.vm.provision "shell", inline: $script

end
